# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/main/linux-64/ca-certificates-2018.03.07-0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libgcc-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libstdcxx-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libffi-3.2.1-hd88cf55_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/ncurses-6.0-h9df7e31_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/openssl-1.0.2o-h20670df_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/tk-8.6.7-hc745277_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.3-h5e939de_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/zlib-1.2.11-ha838bed_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libedit-3.1-heed3624_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/readline-7.0-ha6073c6_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/sqlite-3.23.1-he433501_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.5-hc3d631a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2018.4.16-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-39.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.31.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pip-10.0.1-py36_0.tar.bz2
